language: ruby

sudo: false

rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - ruby-head
  - jruby-9.2.5.0
  - jruby-head

before_install:
  - gem install bundler

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

script: bundle exec rake test

cache: bundler

env:
  - RACK_ENV=development
