title: Shrine
description: File Attachment toolkit for Ruby applications
baseurl: ""
url: https://shrinerb.com
markdown: kramdown
destination: build
plugins:
  - jemoji
exclude:
  - Gemfile
  - Gemfile.lock
defaults:
  -
    scope:
      type: pages
    values:
      layout: default
