title: Shrine
description: Toolkit for file attachments in Ruby applications
baseurl: ""
url: shrinerb.com
markdown: kramdown
destination: build
gems:
  - jemoji
exclude:
  - Gemfile
  - Gemfile.lock
defaults:
  -
    scope:
      type: pages
    values:
      layout: default
